### ISSUE TITLE
Inline Plot Color Broken

### ISSUE THREAD

**Issue by kevinjohncutler** [imatlab/imatlab#57]
Plot color options are not working for all options of `imatlab_export_fig()`. Below is just some test code, which should be plotting a green sine wave on a black background. This is confirmed my direct input into MATLAB and by passing `''` into `imatlab_export_fig()`. However, use of any of the inline options returns a default (blue line on white background) plot. Below is the sample code. 

```
imatlab_export_fig('print-jpeg')
 
%% Time specifications:
Fs = 8000;                   % samples per second
dt = 1/Fs;                   % seconds per sample
StopTime = 0.25;             % seconds
t = (0:dt:StopTime-dt)';     % seconds

%% Sine wave:
Fc = 60;                     % hertz
x = cos(2*pi*Fc*t);

% Plot the signal versus time:
figure;
plot(t,x,'g');
set(gca,'color','k')
xlabel('time (in seconds)');
title('Signal versus Time');
```
It would be ideal to be able to use Ploty's [themes](https://medium.com/@plotlygraphs/introducing-plotly-py-theming-b644109ac9c7), but at minimum it should be possible to produce static images correctly. Issue #6 was getting at that, but I couldn't tell what (if anything) was resolved/developed and I bet there already exists a solution.

**Comment by anntzer** [comment]
I can't repro your issue; this is what I get:
![Screenshot_20190614_010429](https://user-images.githubusercontent.com/1322974/59472917-6bd9d580-8e40-11e9-80b7-1cafb1eee40b.png)

**Comment by kevinjohncutler** [comment]
That is my output too. The code 
```
plot(t,x,'g');
set(gca,'color','k')
```
should be making the background black and the line green. The line color is correct (plus the axes labeling etc. works) but the background is not.

**Comment by kevinjohncutler** [comment]
In addition, I just noticed that the option 'print-svg' combined with `set(gcf,'color','k');` (rather than _or_ in addition to `gca`) removes the title. Not sure why - in native MATLAB it makes the background black. Maybe it is rendering a black title with a black background then flipping it all to white.

**Comment by anntzer** [comment]
Oh, I see, sorry I missed that.
That seems to come from MATLAB itself?  If you generate such a plot (outside of the notebook) and manually save it via the UI or by calling MATLAB's `print` -- the latter is what imatlab does), you also get the white background.  So someone needs to figure out how to make `print` respect the background color...

**Comment by kevinjohncutler** [comment]
Ok, I'll look into `print`. Any idea how I should go about changing the Plotly colors? There is documentation for using Plotly in MATLAB natively, and there is documentation for using Plotly themes in a python script, but nothing on the two taken together. I will see what I can do with the `fig2plotly` command in `imatlab_export_fig.m`.

**Comment by kevinjohncutler** [comment]
Ok, I have a fix for `print`. The crucial property is `InvertHardCopy` for the `gcf` object. Below is code that generates the desired output (note that I am using the dark theme in Jupyter Lab):

```
imatlab_export_fig('print-svg')
 
%% Time specifications:
Fs = 8000;                   % samples per second
dt = 1/Fs;                   % seconds per sample
StopTime = 0.25;             % seconds
t = (0:dt:StopTime-dt)';     % seconds

%% Sine wave:
Fc = 60;                     % hertz
x = cos(2*pi*Fc*t);

% Plot the signal versus time:
close all
figure;


plot(t,x,'g');
xlabel('time (in seconds)');
title('Signal versus Time');
%%fix color. Could also use set()
clr = [.5 .5 .5];

plotArea = gca;
plotArea.FontName = 'Arial';
plotArea.Color = 'none';
plotArea.XColor = clr;
plotArea.YColor = clr;
plotArea.Box = 'off';
plotArea.Title.Color = clr;
plotArea.XLabel.Color = clr;


frame = gcf;
frame.Color = 'none';

frame.InvertHardcopy = 'off'; %This is the critical line to make print respect the colors
```
The actually relevant line for this issue is `frame.InvertHardcopy = 'off';` I am not really familiar with the syntax of `imatlab_export_fig.m`, but I will see if this line can be incorporated into it so that user-defined colors are respected by default. Obviously `children` needs to have that property edited, but nothing I am trying is working...

**Comment by anntzer** [comment]
Thanks, I pushed that fix.
No idea for plotly but once again your investigation is well appreciated :)

**Comment by kevinjohncutler** [comment]
Thanks for pushing the change to `imatlab_export_fig.m`, but it does not seem to fix the issue for me. I've been trying some edits of that file to no avail; it looks like editing the `child` pointer's fields do not affect the original plot. Even explicitly setting` child.Color` within `imatlab_export_fig.m` (while avoiding any edits to the figure in the main script) does not yield any changes to the final figure. 

Perhaps there is some subtle difference between editing the current figure via `gcf` vs the fields attached to a figure handle? Or maybe it it just a syntax issue that we're not seeing.

**Comment by anntzer** [comment]
I can't repro your issue, this is what I get now with matlab2019a and imatlab HEAD:
![screenshot](https://user-images.githubusercontent.com/1322974/60099712-82ddc900-9758-11e9-92c2-eb140bfc53bb.png)

**Comment by kevinjohncutler** [comment]
I got it working by re-installing imatlab and manually re-copying the edited `imatlab_export_fig.m` file into the same folder, since the reinstallation did not appear to change that file. What should I be doing to (a) properly update the files from github and (b) make sure that changes to any files like `imatlab_export_fig.m` are seen by the kernel? As to the latter, it seems like restarting the kernel does the trick, but maybe there is an easier/faster way.

**Comment by anntzer** [comment]
Reinstannling should overwrite the old imatlab_export_fig, so I don't know what happened; likewise it should not be necessary to restart the kernel, but it's also hard to troubleshoot this.
